#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: eaa4f711da30
#
Name     : openvino
Version  : 2024.3.0
Release  : 6
URL      : https://github.com/openvinotoolkit/openvino/archive/2024.3.0/openvino-2024.3.0.tar.gz
Source0  : https://github.com/openvinotoolkit/openvino/archive/2024.3.0/openvino-2024.3.0.tar.gz
Source1  : http://localhost/cgit/projects/openvino-vendor/snapshot/openvino-vendor-2024.3.0.tar.gz
Summary  : Extends sphinx-sitemap plugin with additional sitemap metadata
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: openvino-lib = %{version}-%{release}
Requires: openvino-license = %{version}-%{release}
Requires: openvino-python = %{version}-%{release}
Requires: openvino-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : gflags-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : llvm-dev
BuildRequires : node-addon-api-dev
BuildRequires : nodejs-dev
BuildRequires : opencv-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(hwloc)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(nlohmann_json)
BuildRequires : pkgconfig(tbb)
BuildRequires : pkgconfig(zlib)
BuildRequires : protobuf-dev
BuildRequires : pypi(pybind11)
BuildRequires : pypi-sphinx
BuildRequires : python3-dev
BuildRequires : snappy-dev
BuildRequires : texlive
BuildRequires : wget
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: fix-install-paths.patch
Patch2: 0001-Provide-node.js-include-paths.patch

%description
<div align="center">
<img src="docs/dev/assets/openvino-logo-purple-black.svg" width="400px">

%package dev
Summary: dev components for the openvino package.
Group: Development
Requires: openvino-lib = %{version}-%{release}
Provides: openvino-devel = %{version}-%{release}
Requires: openvino = %{version}-%{release}

%description dev
dev components for the openvino package.


%package lib
Summary: lib components for the openvino package.
Group: Libraries
Requires: openvino-license = %{version}-%{release}

%description lib
lib components for the openvino package.


%package license
Summary: license components for the openvino package.
Group: Default

%description license
license components for the openvino package.


%package python
Summary: python components for the openvino package.
Group: Default
Requires: openvino-python3 = %{version}-%{release}

%description python
python components for the openvino package.


%package python3
Summary: python3 components for the openvino package.
Group: Default
Requires: python3-core
Requires: pypi(numpy)

%description python3
python3 components for the openvino package.


%prep
%setup -q -n openvino-2024.3.0
cd %{_builddir}
mkdir -p openvino-vendor-2024.3.0.tar
cd openvino-vendor-2024.3.0.tar
tar xf %{_sourcedir}/openvino-vendor-2024.3.0.tar.gz
cd %{_builddir}/openvino-2024.3.0
%patch -P 1 -p1
%patch -P 2 -p1

%build
## build_prepend content
# Copy the prepackaged git submodules into place
VENDOR=$(find %{_builddir}/openvino-vendor-* -type d -name vendor -print -quit)
cp -pr "${VENDOR}"/* ./
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1723594423
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DCMAKE_CXX_STANDARD=17 \
-DENABLE_SAMPLES=OFF \
-DENABLE_SYSTEM_FLATBUFFERS=ON \
-DENABLE_SYSTEM_OPENCL=ON \
-DENABLE_SYSTEM_PROTOBUF=ON \
-DENABLE_SYSTEM_PUGIXML=ON \
-DENABLE_SYSTEM_SNAPPY=ON \
-DENABLE_SYSTEM_TBB=ON \
-DFETCHCONTENT_FULLY_DISCONNECTED=ON \
-DFETCHCONTENT_TRY_FIND_PACKAGE_MODE=ALWAYS  -G 'Unix Makefiles'
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1723594423
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openvino
cp %{_builddir}/openvino-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/openvino/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/openvino-%{version}/licensing/dev-third-party-programs.txt %{buildroot}/usr/share/package-licenses/openvino/a5b2ac7995e010a0669a508811f8d1934bc32fa1 || :
cp %{_builddir}/openvino-%{version}/licensing/documentation-third-party-programs.txt %{buildroot}/usr/share/package-licenses/openvino/47b64938688e45d89d89ec39ba952d9cc0055e2a || :
cp %{_builddir}/openvino-%{version}/licensing/onednn_third-party-programs.txt %{buildroot}/usr/share/package-licenses/openvino/ba82c8898e3ad92ce108ededdacb72ee64405e83 || :
cp %{_builddir}/openvino-%{version}/licensing/onetbb_third-party-programs.txt %{buildroot}/usr/share/package-licenses/openvino/e0b5018d042e25a484cc489f48b46a9ef5b96ba3 || :
cp %{_builddir}/openvino-%{version}/licensing/runtime-third-party-programs.txt %{buildroot}/usr/share/package-licenses/openvino/b1cd4f8b1165b1e396c77ee8307ab7603fea2908 || :
cp %{_builddir}/openvino-%{version}/licensing/third-party-programs.txt %{buildroot}/usr/share/package-licenses/openvino/7dd29ddda07eb5b49c4ba04f22c3a1b53acbfe82 || :
cp %{_builddir}/openvino-%{version}/thirdparty/cnpy/LICENSE %{buildroot}/usr/share/package-licenses/openvino/bc03a4e0e3f013c960f89a6e0a303d014f6d43d4 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
rm  -f %{buildroot}/usr/lib/python*/site-packages/requirements.txt
rm -rf %{buildroot}/usr/samples/cpp/thirdparty
rm -rf %{buildroot}/usr/tools
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/openvino/cache.json

%files dev
%defattr(-,root,root,-)
/usr/include/openvino/c/auto/properties.h
/usr/include/openvino/c/deprecated.h
/usr/include/openvino/c/gpu/gpu_plugin_properties.h
/usr/include/openvino/c/openvino.h
/usr/include/openvino/c/ov_common.h
/usr/include/openvino/c/ov_compiled_model.h
/usr/include/openvino/c/ov_core.h
/usr/include/openvino/c/ov_dimension.h
/usr/include/openvino/c/ov_infer_request.h
/usr/include/openvino/c/ov_layout.h
/usr/include/openvino/c/ov_model.h
/usr/include/openvino/c/ov_node.h
/usr/include/openvino/c/ov_partial_shape.h
/usr/include/openvino/c/ov_prepostprocess.h
/usr/include/openvino/c/ov_property.h
/usr/include/openvino/c/ov_rank.h
/usr/include/openvino/c/ov_remote_context.h
/usr/include/openvino/c/ov_shape.h
/usr/include/openvino/c/ov_tensor.h
/usr/include/openvino/core/any.hpp
/usr/include/openvino/core/attribute_adapter.hpp
/usr/include/openvino/core/attribute_visitor.hpp
/usr/include/openvino/core/axis_set.hpp
/usr/include/openvino/core/axis_vector.hpp
/usr/include/openvino/core/coordinate.hpp
/usr/include/openvino/core/coordinate_diff.hpp
/usr/include/openvino/core/core.hpp
/usr/include/openvino/core/core_visibility.hpp
/usr/include/openvino/core/deprecated.hpp
/usr/include/openvino/core/descriptor/input.hpp
/usr/include/openvino/core/descriptor/output.hpp
/usr/include/openvino/core/descriptor/tensor.hpp
/usr/include/openvino/core/dimension.hpp
/usr/include/openvino/core/enum_mask.hpp
/usr/include/openvino/core/enum_names.hpp
/usr/include/openvino/core/except.hpp
/usr/include/openvino/core/extension.hpp
/usr/include/openvino/core/graph_util.hpp
/usr/include/openvino/core/interval.hpp
/usr/include/openvino/core/layout.hpp
/usr/include/openvino/core/model.hpp
/usr/include/openvino/core/node.hpp
/usr/include/openvino/core/node_input.hpp
/usr/include/openvino/core/node_output.hpp
/usr/include/openvino/core/node_vector.hpp
/usr/include/openvino/core/op_extension.hpp
/usr/include/openvino/core/parallel.hpp
/usr/include/openvino/core/partial_shape.hpp
/usr/include/openvino/core/preprocess/color_format.hpp
/usr/include/openvino/core/preprocess/input_info.hpp
/usr/include/openvino/core/preprocess/input_model_info.hpp
/usr/include/openvino/core/preprocess/input_tensor_info.hpp
/usr/include/openvino/core/preprocess/output_info.hpp
/usr/include/openvino/core/preprocess/output_model_info.hpp
/usr/include/openvino/core/preprocess/output_tensor_info.hpp
/usr/include/openvino/core/preprocess/padding_mode.hpp
/usr/include/openvino/core/preprocess/postprocess_steps.hpp
/usr/include/openvino/core/preprocess/pre_post_process.hpp
/usr/include/openvino/core/preprocess/preprocess_steps.hpp
/usr/include/openvino/core/preprocess/resize_algorithm.hpp
/usr/include/openvino/core/rank.hpp
/usr/include/openvino/core/rt_info.hpp
/usr/include/openvino/core/rtti.hpp
/usr/include/openvino/core/runtime_attribute.hpp
/usr/include/openvino/core/shape.hpp
/usr/include/openvino/core/strides.hpp
/usr/include/openvino/core/symbol.hpp
/usr/include/openvino/core/type.hpp
/usr/include/openvino/core/type/bfloat16.hpp
/usr/include/openvino/core/type/element_type.hpp
/usr/include/openvino/core/type/element_type_traits.hpp
/usr/include/openvino/core/type/float16.hpp
/usr/include/openvino/core/type/float4_e2m1.hpp
/usr/include/openvino/core/type/float8_e4m3.hpp
/usr/include/openvino/core/type/float8_e5m2.hpp
/usr/include/openvino/core/type/float8_e8m0.hpp
/usr/include/openvino/core/version.hpp
/usr/include/openvino/core/visibility.hpp
/usr/include/openvino/frontend/complex_type_mark.hpp
/usr/include/openvino/frontend/decoder.hpp
/usr/include/openvino/frontend/exception.hpp
/usr/include/openvino/frontend/extension.hpp
/usr/include/openvino/frontend/extension/conversion.hpp
/usr/include/openvino/frontend/extension/decoder_transformation.hpp
/usr/include/openvino/frontend/extension/holder.hpp
/usr/include/openvino/frontend/extension/op.hpp
/usr/include/openvino/frontend/extension/progress_reporter.hpp
/usr/include/openvino/frontend/extension/telemetry.hpp
/usr/include/openvino/frontend/frontend.hpp
/usr/include/openvino/frontend/graph_iterator.hpp
/usr/include/openvino/frontend/input_model.hpp
/usr/include/openvino/frontend/manager.hpp
/usr/include/openvino/frontend/node_context.hpp
/usr/include/openvino/frontend/onnx/extension/conversion.hpp
/usr/include/openvino/frontend/onnx/extension/op.hpp
/usr/include/openvino/frontend/onnx/frontend.hpp
/usr/include/openvino/frontend/onnx/node_context.hpp
/usr/include/openvino/frontend/onnx/visibility.hpp
/usr/include/openvino/frontend/paddle/decoder.hpp
/usr/include/openvino/frontend/paddle/exception.hpp
/usr/include/openvino/frontend/paddle/extension/conversion.hpp
/usr/include/openvino/frontend/paddle/extension/op.hpp
/usr/include/openvino/frontend/paddle/frontend.hpp
/usr/include/openvino/frontend/paddle/node_context.hpp
/usr/include/openvino/frontend/paddle/visibility.hpp
/usr/include/openvino/frontend/place.hpp
/usr/include/openvino/frontend/pytorch/decoder.hpp
/usr/include/openvino/frontend/pytorch/extension/conversion.hpp
/usr/include/openvino/frontend/pytorch/extension/op.hpp
/usr/include/openvino/frontend/pytorch/frontend.hpp
/usr/include/openvino/frontend/pytorch/node_context.hpp
/usr/include/openvino/frontend/pytorch/visibility.hpp
/usr/include/openvino/frontend/tensorflow/decoder.hpp
/usr/include/openvino/frontend/tensorflow/exception.hpp
/usr/include/openvino/frontend/tensorflow/extension/conversion.hpp
/usr/include/openvino/frontend/tensorflow/extension/op.hpp
/usr/include/openvino/frontend/tensorflow/frontend.hpp
/usr/include/openvino/frontend/tensorflow/hash_table.hpp
/usr/include/openvino/frontend/tensorflow/node_context.hpp
/usr/include/openvino/frontend/tensorflow/special_types.hpp
/usr/include/openvino/frontend/tensorflow/variable.hpp
/usr/include/openvino/frontend/tensorflow/variables_map.hpp
/usr/include/openvino/frontend/tensorflow/visibility.hpp
/usr/include/openvino/frontend/tensorflow_lite/decoder.hpp
/usr/include/openvino/frontend/tensorflow_lite/extension/conversion.hpp
/usr/include/openvino/frontend/tensorflow_lite/extension/op.hpp
/usr/include/openvino/frontend/tensorflow_lite/frontend.hpp
/usr/include/openvino/frontend/tensorflow_lite/graph_iterator.hpp
/usr/include/openvino/frontend/tensorflow_lite/node_context.hpp
/usr/include/openvino/frontend/tensorflow_lite/quantization_info.hpp
/usr/include/openvino/frontend/tensorflow_lite/sparsity_info.hpp
/usr/include/openvino/frontend/tensorflow_lite/visibility.hpp
/usr/include/openvino/frontend/visibility.hpp
/usr/include/openvino/op/abs.hpp
/usr/include/openvino/op/acos.hpp
/usr/include/openvino/op/acosh.hpp
/usr/include/openvino/op/adaptive_avg_pool.hpp
/usr/include/openvino/op/adaptive_max_pool.hpp
/usr/include/openvino/op/add.hpp
/usr/include/openvino/op/asin.hpp
/usr/include/openvino/op/asinh.hpp
/usr/include/openvino/op/assign.hpp
/usr/include/openvino/op/atan.hpp
/usr/include/openvino/op/atanh.hpp
/usr/include/openvino/op/avg_pool.hpp
/usr/include/openvino/op/batch_norm.hpp
/usr/include/openvino/op/batch_to_space.hpp
/usr/include/openvino/op/binary_convolution.hpp
/usr/include/openvino/op/bitwise_and.hpp
/usr/include/openvino/op/bitwise_not.hpp
/usr/include/openvino/op/bitwise_or.hpp
/usr/include/openvino/op/bitwise_xor.hpp
/usr/include/openvino/op/broadcast.hpp
/usr/include/openvino/op/bucketize.hpp
/usr/include/openvino/op/ceiling.hpp
/usr/include/openvino/op/clamp.hpp
/usr/include/openvino/op/col2im.hpp
/usr/include/openvino/op/concat.hpp
/usr/include/openvino/op/constant.hpp
/usr/include/openvino/op/convert.hpp
/usr/include/openvino/op/convert_like.hpp
/usr/include/openvino/op/convert_promote_types.hpp
/usr/include/openvino/op/convolution.hpp
/usr/include/openvino/op/cos.hpp
/usr/include/openvino/op/cosh.hpp
/usr/include/openvino/op/ctc_greedy_decoder.hpp
/usr/include/openvino/op/ctc_greedy_decoder_seq_len.hpp
/usr/include/openvino/op/ctc_loss.hpp
/usr/include/openvino/op/cum_sum.hpp
/usr/include/openvino/op/deformable_convolution.hpp
/usr/include/openvino/op/deformable_psroi_pooling.hpp
/usr/include/openvino/op/depth_to_space.hpp
/usr/include/openvino/op/detection_output.hpp
/usr/include/openvino/op/dft.hpp
/usr/include/openvino/op/divide.hpp
/usr/include/openvino/op/einsum.hpp
/usr/include/openvino/op/elu.hpp
/usr/include/openvino/op/embedding_segments_sum.hpp
/usr/include/openvino/op/embeddingbag_offsets.hpp
/usr/include/openvino/op/embeddingbag_offsets_sum.hpp
/usr/include/openvino/op/embeddingbag_packed.hpp
/usr/include/openvino/op/embeddingbag_packedsum.hpp
/usr/include/openvino/op/equal.hpp
/usr/include/openvino/op/erf.hpp
/usr/include/openvino/op/exp.hpp
/usr/include/openvino/op/experimental_detectron_detection_output.hpp
/usr/include/openvino/op/experimental_detectron_generate_proposals.hpp
/usr/include/openvino/op/experimental_detectron_prior_grid_generator.hpp
/usr/include/openvino/op/experimental_detectron_roi_feature.hpp
/usr/include/openvino/op/experimental_detectron_topkrois.hpp
/usr/include/openvino/op/extractimagepatches.hpp
/usr/include/openvino/op/eye.hpp
/usr/include/openvino/op/fake_convert.hpp
/usr/include/openvino/op/fake_quantize.hpp
/usr/include/openvino/op/floor.hpp
/usr/include/openvino/op/floor_mod.hpp
/usr/include/openvino/op/gather.hpp
/usr/include/openvino/op/gather_elements.hpp
/usr/include/openvino/op/gather_nd.hpp
/usr/include/openvino/op/gather_tree.hpp
/usr/include/openvino/op/gelu.hpp
/usr/include/openvino/op/generate_proposals.hpp
/usr/include/openvino/op/greater.hpp
/usr/include/openvino/op/greater_eq.hpp
/usr/include/openvino/op/grid_sample.hpp
/usr/include/openvino/op/grn.hpp
/usr/include/openvino/op/group_conv.hpp
/usr/include/openvino/op/group_normalization.hpp
/usr/include/openvino/op/gru_cell.hpp
/usr/include/openvino/op/gru_sequence.hpp
/usr/include/openvino/op/hard_sigmoid.hpp
/usr/include/openvino/op/hsigmoid.hpp
/usr/include/openvino/op/hswish.hpp
/usr/include/openvino/op/i420_to_bgr.hpp
/usr/include/openvino/op/i420_to_rgb.hpp
/usr/include/openvino/op/idft.hpp
/usr/include/openvino/op/if.hpp
/usr/include/openvino/op/interpolate.hpp
/usr/include/openvino/op/inverse.hpp
/usr/include/openvino/op/irdft.hpp
/usr/include/openvino/op/is_finite.hpp
/usr/include/openvino/op/is_inf.hpp
/usr/include/openvino/op/is_nan.hpp
/usr/include/openvino/op/less.hpp
/usr/include/openvino/op/less_eq.hpp
/usr/include/openvino/op/log.hpp
/usr/include/openvino/op/log_softmax.hpp
/usr/include/openvino/op/logical_and.hpp
/usr/include/openvino/op/logical_not.hpp
/usr/include/openvino/op/logical_or.hpp
/usr/include/openvino/op/logical_xor.hpp
/usr/include/openvino/op/loop.hpp
/usr/include/openvino/op/lrn.hpp
/usr/include/openvino/op/lstm_cell.hpp
/usr/include/openvino/op/lstm_sequence.hpp
/usr/include/openvino/op/matmul.hpp
/usr/include/openvino/op/matrix_nms.hpp
/usr/include/openvino/op/max_pool.hpp
/usr/include/openvino/op/maximum.hpp
/usr/include/openvino/op/minimum.hpp
/usr/include/openvino/op/mish.hpp
/usr/include/openvino/op/mod.hpp
/usr/include/openvino/op/multiclass_nms.hpp
/usr/include/openvino/op/multinomial.hpp
/usr/include/openvino/op/multiply.hpp
/usr/include/openvino/op/mvn.hpp
/usr/include/openvino/op/negative.hpp
/usr/include/openvino/op/nms_rotated.hpp
/usr/include/openvino/op/non_max_suppression.hpp
/usr/include/openvino/op/non_zero.hpp
/usr/include/openvino/op/normalize_l2.hpp
/usr/include/openvino/op/not_equal.hpp
/usr/include/openvino/op/nv12_to_bgr.hpp
/usr/include/openvino/op/nv12_to_rgb.hpp
/usr/include/openvino/op/one_hot.hpp
/usr/include/openvino/op/op.hpp
/usr/include/openvino/op/ops.hpp
/usr/include/openvino/op/pad.hpp
/usr/include/openvino/op/parameter.hpp
/usr/include/openvino/op/power.hpp
/usr/include/openvino/op/prelu.hpp
/usr/include/openvino/op/prior_box.hpp
/usr/include/openvino/op/prior_box_clustered.hpp
/usr/include/openvino/op/proposal.hpp
/usr/include/openvino/op/psroi_pooling.hpp
/usr/include/openvino/op/random_uniform.hpp
/usr/include/openvino/op/range.hpp
/usr/include/openvino/op/rdft.hpp
/usr/include/openvino/op/read_value.hpp
/usr/include/openvino/op/reduce_l1.hpp
/usr/include/openvino/op/reduce_l2.hpp
/usr/include/openvino/op/reduce_logical_and.hpp
/usr/include/openvino/op/reduce_logical_or.hpp
/usr/include/openvino/op/reduce_max.hpp
/usr/include/openvino/op/reduce_mean.hpp
/usr/include/openvino/op/reduce_min.hpp
/usr/include/openvino/op/reduce_prod.hpp
/usr/include/openvino/op/reduce_sum.hpp
/usr/include/openvino/op/region_yolo.hpp
/usr/include/openvino/op/relu.hpp
/usr/include/openvino/op/reorg_yolo.hpp
/usr/include/openvino/op/reshape.hpp
/usr/include/openvino/op/result.hpp
/usr/include/openvino/op/reverse.hpp
/usr/include/openvino/op/reverse_sequence.hpp
/usr/include/openvino/op/rnn_cell.hpp
/usr/include/openvino/op/rnn_sequence.hpp
/usr/include/openvino/op/roi_align.hpp
/usr/include/openvino/op/roi_align_rotated.hpp
/usr/include/openvino/op/roi_pooling.hpp
/usr/include/openvino/op/roll.hpp
/usr/include/openvino/op/round.hpp
/usr/include/openvino/op/scaled_dot_product_attention.hpp
/usr/include/openvino/op/scatter_elements_update.hpp
/usr/include/openvino/op/scatter_nd_update.hpp
/usr/include/openvino/op/scatter_update.hpp
/usr/include/openvino/op/select.hpp
/usr/include/openvino/op/selu.hpp
/usr/include/openvino/op/shape_of.hpp
/usr/include/openvino/op/shuffle_channels.hpp
/usr/include/openvino/op/sigmoid.hpp
/usr/include/openvino/op/sign.hpp
/usr/include/openvino/op/sin.hpp
/usr/include/openvino/op/sinh.hpp
/usr/include/openvino/op/sink.hpp
/usr/include/openvino/op/slice.hpp
/usr/include/openvino/op/softmax.hpp
/usr/include/openvino/op/softplus.hpp
/usr/include/openvino/op/softsign.hpp
/usr/include/openvino/op/space_to_batch.hpp
/usr/include/openvino/op/space_to_depth.hpp
/usr/include/openvino/op/split.hpp
/usr/include/openvino/op/sqrt.hpp
/usr/include/openvino/op/squared_difference.hpp
/usr/include/openvino/op/squeeze.hpp
/usr/include/openvino/op/strided_slice.hpp
/usr/include/openvino/op/subtract.hpp
/usr/include/openvino/op/swish.hpp
/usr/include/openvino/op/tan.hpp
/usr/include/openvino/op/tanh.hpp
/usr/include/openvino/op/tensor_iterator.hpp
/usr/include/openvino/op/tile.hpp
/usr/include/openvino/op/topk.hpp
/usr/include/openvino/op/transpose.hpp
/usr/include/openvino/op/unique.hpp
/usr/include/openvino/op/unsqueeze.hpp
/usr/include/openvino/op/util/activation_functions.hpp
/usr/include/openvino/op/util/arithmetic_reduction.hpp
/usr/include/openvino/op/util/arithmetic_reductions_keep_dims.hpp
/usr/include/openvino/op/util/assign_base.hpp
/usr/include/openvino/op/util/attr_types.hpp
/usr/include/openvino/op/util/avg_pool_base.hpp
/usr/include/openvino/op/util/axes_util.hpp
/usr/include/openvino/op/util/binary_elementwise_arithmetic.hpp
/usr/include/openvino/op/util/binary_elementwise_bitwise.hpp
/usr/include/openvino/op/util/binary_elementwise_comparison.hpp
/usr/include/openvino/op/util/binary_elementwise_logical.hpp
/usr/include/openvino/op/util/broadcast_base.hpp
/usr/include/openvino/op/util/convert_color_i420_base.hpp
/usr/include/openvino/op/util/convert_color_nv12_base.hpp
/usr/include/openvino/op/util/convolution_backprop_base.hpp
/usr/include/openvino/op/util/convolution_base.hpp
/usr/include/openvino/op/util/deformable_convolution_base.hpp
/usr/include/openvino/op/util/detection_output_base.hpp
/usr/include/openvino/op/util/elementwise_args.hpp
/usr/include/openvino/op/util/embeddingbag_offsets_base.hpp
/usr/include/openvino/op/util/embeddingbag_packed_base.hpp
/usr/include/openvino/op/util/fft_base.hpp
/usr/include/openvino/op/util/framework_node.hpp
/usr/include/openvino/op/util/gather_base.hpp
/usr/include/openvino/op/util/gather_nd_base.hpp
/usr/include/openvino/op/util/index_reduction.hpp
/usr/include/openvino/op/util/interpolate_base.hpp
/usr/include/openvino/op/util/logical_reduction.hpp
/usr/include/openvino/op/util/logical_reduction_keep_dims.hpp
/usr/include/openvino/op/util/max_pool_base.hpp
/usr/include/openvino/op/util/multi_subgraph_base.hpp
/usr/include/openvino/op/util/multiclass_nms_base.hpp
/usr/include/openvino/op/util/op_types.hpp
/usr/include/openvino/op/util/pad_base.hpp
/usr/include/openvino/op/util/precision_sensitive_attribute.hpp
/usr/include/openvino/op/util/read_value_base.hpp
/usr/include/openvino/op/util/recurrent_sequence.hpp
/usr/include/openvino/op/util/reduction_base.hpp
/usr/include/openvino/op/util/rnn_cell_base.hpp
/usr/include/openvino/op/util/roi_align_base.hpp
/usr/include/openvino/op/util/scatter_base.hpp
/usr/include/openvino/op/util/scatter_elements_update_base.hpp
/usr/include/openvino/op/util/scatter_nd_base.hpp
/usr/include/openvino/op/util/shape_of_base.hpp
/usr/include/openvino/op/util/sub_graph_base.hpp
/usr/include/openvino/op/util/symbolic_info.hpp
/usr/include/openvino/op/util/topk_base.hpp
/usr/include/openvino/op/util/unary_elementwise_arithmetic.hpp
/usr/include/openvino/op/util/variable.hpp
/usr/include/openvino/op/util/variable_context.hpp
/usr/include/openvino/op/util/variable_extension.hpp
/usr/include/openvino/op/util/variable_value.hpp
/usr/include/openvino/op/variadic_split.hpp
/usr/include/openvino/op/xor.hpp
/usr/include/openvino/openvino.hpp
/usr/include/openvino/opsets/opset.hpp
/usr/include/openvino/opsets/opset1.hpp
/usr/include/openvino/opsets/opset10.hpp
/usr/include/openvino/opsets/opset10_tbl.hpp
/usr/include/openvino/opsets/opset11.hpp
/usr/include/openvino/opsets/opset11_tbl.hpp
/usr/include/openvino/opsets/opset12.hpp
/usr/include/openvino/opsets/opset12_tbl.hpp
/usr/include/openvino/opsets/opset13.hpp
/usr/include/openvino/opsets/opset13_tbl.hpp
/usr/include/openvino/opsets/opset14.hpp
/usr/include/openvino/opsets/opset14_tbl.hpp
/usr/include/openvino/opsets/opset15.hpp
/usr/include/openvino/opsets/opset15_tbl.hpp
/usr/include/openvino/opsets/opset1_tbl.hpp
/usr/include/openvino/opsets/opset2.hpp
/usr/include/openvino/opsets/opset2_tbl.hpp
/usr/include/openvino/opsets/opset3.hpp
/usr/include/openvino/opsets/opset3_tbl.hpp
/usr/include/openvino/opsets/opset4.hpp
/usr/include/openvino/opsets/opset4_tbl.hpp
/usr/include/openvino/opsets/opset5.hpp
/usr/include/openvino/opsets/opset5_tbl.hpp
/usr/include/openvino/opsets/opset6.hpp
/usr/include/openvino/opsets/opset6_tbl.hpp
/usr/include/openvino/opsets/opset7.hpp
/usr/include/openvino/opsets/opset7_tbl.hpp
/usr/include/openvino/opsets/opset8.hpp
/usr/include/openvino/opsets/opset8_tbl.hpp
/usr/include/openvino/opsets/opset9.hpp
/usr/include/openvino/opsets/opset9_tbl.hpp
/usr/include/openvino/pass/constant_folding.hpp
/usr/include/openvino/pass/convert_fp32_to_fp16.hpp
/usr/include/openvino/pass/graph_rewrite.hpp
/usr/include/openvino/pass/low_latency.hpp
/usr/include/openvino/pass/make_stateful.hpp
/usr/include/openvino/pass/manager.hpp
/usr/include/openvino/pass/pass.hpp
/usr/include/openvino/pass/pass_config.hpp
/usr/include/openvino/pass/pattern/matcher.hpp
/usr/include/openvino/pass/pattern/op/any.hpp
/usr/include/openvino/pass/pattern/op/any_of.hpp
/usr/include/openvino/pass/pattern/op/any_output.hpp
/usr/include/openvino/pass/pattern/op/label.hpp
/usr/include/openvino/pass/pattern/op/optional.hpp
/usr/include/openvino/pass/pattern/op/or.hpp
/usr/include/openvino/pass/pattern/op/pattern.hpp
/usr/include/openvino/pass/pattern/op/true.hpp
/usr/include/openvino/pass/pattern/op/wrap_type.hpp
/usr/include/openvino/pass/sdpa_to_paged_attention.hpp
/usr/include/openvino/pass/serialize.hpp
/usr/include/openvino/pass/stateful_to_stateless.hpp
/usr/include/openvino/pass/validate.hpp
/usr/include/openvino/pass/visualize_tree.hpp
/usr/include/openvino/runtime/allocator.hpp
/usr/include/openvino/runtime/auto/properties.hpp
/usr/include/openvino/runtime/common.hpp
/usr/include/openvino/runtime/compiled_model.hpp
/usr/include/openvino/runtime/core.hpp
/usr/include/openvino/runtime/exception.hpp
/usr/include/openvino/runtime/infer_request.hpp
/usr/include/openvino/runtime/intel_cpu/properties.hpp
/usr/include/openvino/runtime/intel_gpu/ocl/dx.hpp
/usr/include/openvino/runtime/intel_gpu/ocl/ocl.hpp
/usr/include/openvino/runtime/intel_gpu/ocl/ocl_wrapper.hpp
/usr/include/openvino/runtime/intel_gpu/ocl/va.hpp
/usr/include/openvino/runtime/intel_gpu/properties.hpp
/usr/include/openvino/runtime/intel_gpu/remote_properties.hpp
/usr/include/openvino/runtime/intel_npu/properties.hpp
/usr/include/openvino/runtime/profiling_info.hpp
/usr/include/openvino/runtime/properties.hpp
/usr/include/openvino/runtime/remote_context.hpp
/usr/include/openvino/runtime/remote_tensor.hpp
/usr/include/openvino/runtime/runtime.hpp
/usr/include/openvino/runtime/tensor.hpp
/usr/include/openvino/runtime/variable_state.hpp
/usr/lib64/cmake/OpenVINOConfig-version.cmake
/usr/lib64/cmake/OpenVINOConfig.cmake
/usr/lib64/cmake/OpenVINOTargets-relwithdebinfo.cmake
/usr/lib64/cmake/OpenVINOTargets.cmake
/usr/lib64/libopenvino.so
/usr/lib64/libopenvino_c.so
/usr/lib64/libopenvino_onnx_frontend.so
/usr/lib64/libopenvino_paddle_frontend.so
/usr/lib64/libopenvino_pytorch_frontend.so
/usr/lib64/libopenvino_tensorflow_frontend.so
/usr/lib64/libopenvino_tensorflow_lite_frontend.so
/usr/lib64/pkgconfig/openvino.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopenvino.so.2024.3.0
/usr/lib64/libopenvino.so.2430
/usr/lib64/libopenvino_c.so.2024.3.0
/usr/lib64/libopenvino_c.so.2430
/usr/lib64/libopenvino_ir_frontend.so.2024.3.0
/usr/lib64/libopenvino_ir_frontend.so.2430
/usr/lib64/libopenvino_onnx_frontend.so.2024.3.0
/usr/lib64/libopenvino_onnx_frontend.so.2430
/usr/lib64/libopenvino_paddle_frontend.so.2024.3.0
/usr/lib64/libopenvino_paddle_frontend.so.2430
/usr/lib64/libopenvino_pytorch_frontend.so.2024.3.0
/usr/lib64/libopenvino_pytorch_frontend.so.2430
/usr/lib64/libopenvino_tensorflow_frontend.so.2024.3.0
/usr/lib64/libopenvino_tensorflow_frontend.so.2430
/usr/lib64/libopenvino_tensorflow_lite_frontend.so.2024.3.0
/usr/lib64/libopenvino_tensorflow_lite_frontend.so.2430
/usr/lib64/openvino/libopenvino_auto_batch_plugin.so
/usr/lib64/openvino/libopenvino_auto_plugin.so
/usr/lib64/openvino/libopenvino_hetero_plugin.so
/usr/lib64/openvino/libopenvino_intel_cpu_plugin.so
/usr/lib64/openvino/libopenvino_intel_gpu_plugin.so
/usr/lib64/openvino/libopenvino_intel_npu_plugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openvino/47b64938688e45d89d89ec39ba952d9cc0055e2a
/usr/share/package-licenses/openvino/7dd29ddda07eb5b49c4ba04f22c3a1b53acbfe82
/usr/share/package-licenses/openvino/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/openvino/a5b2ac7995e010a0669a508811f8d1934bc32fa1
/usr/share/package-licenses/openvino/b1cd4f8b1165b1e396c77ee8307ab7603fea2908
/usr/share/package-licenses/openvino/ba82c8898e3ad92ce108ededdacb72ee64405e83
/usr/share/package-licenses/openvino/bc03a4e0e3f013c960f89a6e0a303d014f6d43d4
/usr/share/package-licenses/openvino/e0b5018d042e25a484cc489f48b46a9ef5b96ba3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
